// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAdAJyOosnVQKTJX7cApCuDTHNNwY4JYs',
    appId: '1:222544032929:web:384fb132196e8af5d8ace0',
    messagingSenderId: '222544032929',
    projectId: 'sillentsos',
    authDomain: 'sillentsos.firebaseapp.com',
    storageBucket: 'sillentsos.firebasestorage.app',
    measurementId: 'G-GT6VP6R89X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxXsikzwwuUArGOltcELDuO3AfeSpgFc4',
    appId: '1:222544032929:android:0ca94d7f1f277c69d8ace0',
    messagingSenderId: '222544032929',
    projectId: 'sillentsos',
    storageBucket: 'sillentsos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTsS-zD5QRSPKDIQBKH8gO4EXKDc8WRD0',
    appId: '1:222544032929:ios:73e2e0370b8538e7d8ace0',
    messagingSenderId: '222544032929',
    projectId: 'sillentsos',
    storageBucket: 'sillentsos.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTsS-zD5QRSPKDIQBKH8gO4EXKDc8WRD0',
    appId: '1:222544032929:ios:73e2e0370b8538e7d8ace0',
    messagingSenderId: '222544032929',
    projectId: 'sillentsos',
    storageBucket: 'sillentsos.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAdAJyOosnVQKTJX7cApCuDTHNNwY4JYs',
    appId: '1:222544032929:web:afbeec89d99a08ecd8ace0',
    messagingSenderId: '222544032929',
    projectId: 'sillentsos',
    authDomain: 'sillentsos.firebaseapp.com',
    storageBucket: 'sillentsos.firebasestorage.app',
    measurementId: 'G-7HXT57Z91K',
  );
}
